### ISSUE TITLE
Items we still need from HHS

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov-usability#12]
**Here are some of the things we still need from the team at HHS:**

- [ ] A list of all the sub-domains that are currently attached to the usability.gov domain. (e.g. `guidelines.usability.gov`).
- [ ] a full database export of https://guidelines.usability.gov/ and https://usability.gov/
- [ ] a ZIP of all the files (PDFs, WordDocs, Images) that are associated with https://usability.gov/ and https://guidelines.usability.gov/ 
- [x] Admin access to the Usabilty.gov Google Tag Manager account
- [x] Admin access to the Usabilty.gov Google Analytics account — We'd like to keep that same account since it has the historical data.
- [x] Admin access to the Usabilty.gov Twitter account
- [ ] Admin access to the Usabilty.gov Web Masters Console

**Comment by nick-mon1** [comment]
Closing for archiving.
