### ISSUE TITLE
Update the footer with GSA links

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov-usability#16]
The Footer still contains links to many of the HHS pages.
We should replace them out with the the correct GSA links.

Related: https://github.com/GSA/digitalgov-usability/issues/17

![image](https://user-images.githubusercontent.com/395641/76353192-a9439480-62e6-11ea-978c-8dd8c65f4199.png)

**Comment by nick-mon1** [comment]
Closing for archiving.
