### ISSUE TITLE
Broken sub-domain link on About page

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-usability#31]
From a member of the public: https://www.usability.gov/about-us/index.html 

towards the end:

> Citing The Research-Based Web Design & Usability Guidelines
> HHS developed [The Research-Based Web Design & Usability Guidelines](http://guidelines.usability.gov/), Enlarged/Expanded edition in partnership with the U.S. General Services Administration (GSA).

http://guidelines.usability.gov/ doesn't work. Where is this content?

**Comment by saracope** [comment]
Action:
Redirect guidelines.usability.gov to the usability guidelines book (.pdf)

**Comment by saracope** [comment]
https://www.usability.gov/sites/default/files/documents/guidelines_book.pdf

**Comment by Gabr1elleKING** [comment]
@ToniBonittoGSA if you need help with the redirect let me know. Probably way above my knowledge base but I can definitely learn up!

**Comment by Gabr1elleKING** [comment]
From FDA, HHS on 10/252021, reporting broken links: 

- The link to “Guidelines” (guidelines.usability.gov) associated with the graphic on the left side leads to an error messages. “We can’t connect to the server at guidelines.usability.gov” (Firefox) and “This site can’t be reached” (Chrome).

- On the “Get Involved” page (https://www.usability.gov/get-involved/index.html): The footer’s formatting isn’t displayed correctly.

- 404 errors when I click the footer links “About Us”( https://www.usability.gov/get-involved/about-us/index.html) and “Tour the Site” (https://www.usability.gov/get-involved/site-tour.html).

**Comment by Gabr1elleKING** [comment]
Member of the public ( balsamiq.com>) on 10/06 reporting broken link: 

- https://guidelines.usability.gov/ is missing. It's linked from all pages on https://www.usability.gov/. It's a very important resource - I hope you can fix it soon!

**Comment by Gabr1elleKING** [comment]
Email on 11/22 from private citizen to the DG inbox about this page: https://www.usability.gov/about-us/index.html
The error/problem is : Broken link on page. Specifically, "The Research-Based Web Design & Usability Guidelines" link (target URL: guidelines.usability.gov) on the "About Us" page. Please see the screenshot below.

**Comment by ToniBonittoGSA** [comment]
Links to https://guidelines.usability.gov/ were changed to https://www.usability.gov/sites/default/files/documents/guidelines_book.pdf 

Footer formatting is a separate Issue

site tour links updated
