### ISSUE TITLE
Guidelines Page https://guidelines.usability.gov/

### ISSUE THREAD

**Issue by Gabr1elleKING** [GSA/digitalgov-usability#38]
Email on 5/17 from CA.gov employee to the DG inbox about this page: https://guidelines.usability.gov/
The error/problem is : Hyperlink to Guidelines page from https://www.usability.gov/index.html is not visible (broken link 404 error)

**Comment by ToniBonittoGSA** [comment]
See https://github.com/GSA/digitalgov-usability/issues/31 
Sara made a suggestion, but I will need help implementing it
