### ISSUE TITLE
Broken link to guidelines

### ISSUE THREAD

**Issue by lchidlow** [GSA/digitalgov-usability#39]
https://www.usability.gov/

Link to Guidelines give a 404: https://guidelines.usability.gov/

**Comment by Gabr1elleKING** [comment]
@lchidlow do you know what this is for? Going to close this PR since it is open already under #31 will wait to close until you confirm

**Comment by lchidlow** [comment]
Yes, it's as described in the comments - when you go to https://www.usability.gov/, and then click on the Guidelines button, you get a 404. It's sort of duplicate - but not exactly the same since the button is on the main page. The fix would be the same, though.

**Comment by ToniBonittoGSA** [comment]
was fixed
