### ISSUE TITLE
Broken links on what and why

### ISSUE THREAD

**Issue by lchidlow** [GSA/digitalgov-usability#41]
https://www.usability.gov/what-and-why/index.html 

The 11 links under UX Discipline return 404s if you click on the folder image vs the folder name.

**Comment by Gabr1elleKING** [comment]
Member of the public, email sent on 11/15/2021: 

- I was just at your page What & Why of Usability: https://www.usability.gov/what-and-why/index.html
- The first link I tried, User Experience Basics, produced a 404.

**Comment by ToniBonittoGSA** [comment]
All were fixed; closing
