### ISSUE TITLE
Broken link for Content Strategy Quad

### ISSUE THREAD

**Issue by lchidlow** [GSA/digitalgov-usability#43]
https://www.usability.gov/what-and-why/content-strategy.html

When you click on the link for "Content Strategy Quad," the site cannot be reached: https://www.blog.braintraffic.com/2012/07/from-the-archive-brain-traffic-lands-the-quad

**Comment by ToniBonittoGSA** [comment]
Blog was reformated; now at https://www.braintraffic.com/blog/brain-traffic-lands-the-quad; fixed
