### ISSUE TITLE
Broken Link: How to and Tools for System Usability Scale reference

### ISSUE THREAD

**Issue by Gabr1elleKING** [GSA/digitalgov-usability#44]
Email received from member of the public on 11/30 to the DG inbox.
Issue / Error: The link to the system usability scale (SUS) template from the Usability.gov page below is no longer valid. Looks like the site has been abandoned. https://www.usability.gov/how-to-and-tools/resources/templates/system-usability-scale-sus.html

**Comment by Gabr1elleKING** [comment]
Email received from member of the public on 12/16 to the DG inbox.
Issue / Error: 
At the bottom of https://www.usability.gov/how-to-and-tools/methods/card-sorting.html, you have a link to UsabilityNet's Card Sorting Summary. That link points to an expired domain.
Suggest removing link to expired page.

**Comment by Gabr1elleKING** [comment]
Email received from federal employee from DHS USCIS Office of Information Technology (OIT) on 12/7 to the DG inbox.
Issue / Error:
"I have been pointed to https://www.usability.gov/how-to-and-tools/guidance/fast-track-clearance-process.html to help with sharing out information on the PRA Fast Track process. There is a link to howto.gov on this page about what falls under the Fast Track process. It’s my understanding that HowTo.gov no longer exists. Is there a similar resource that you would recommend me pointing folks to? Is there a plan to replace howto.gov URLs on Usability.gov?"

Suggest: update and replace all howto.gov urls linked to the site.

**Comment by ToniBonittoGSA** [comment]
All 3 were fixed
