### ISSUE TITLE
Replace Search source

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov-usability#9]
Currently, Usability.gov is using a service at HHS for site-wide search. We will need to replace that with our own.

I suggest that we index the content in the Digital.gov search instance and use that.
We can even make a separate tab in the search interface for just indexing that site.

In theory, this can be done anytime, as the sitemap should be the same now (while at HHS) as it will be when it is on Federalist.

## To-do

- [x] Replace out the search
- [ ] submit the sitemap to Search.gov

**Comment by nick-mon1** [comment]
Closing for archiving.
